### ISSUE TITLE
School Login

### ISSUE THREAD

**Issue by Dragomirc** [fac-12/homesafe#13]
As a school, I want to be able to login to HomeSafe quickly so that I can check the pick up requests made by parents.
This will include:

 - [x] A login form with email, password and a submit button
 - [x] Create the query check_school
 - [x] Create /login_school route
- [x] Create the query check_school_password

As a stretch goal:
- [ ] have a 'forgot your password?' link

**Comment by Gbaja** [comment]
Decided not to have the print option in this build

**Comment by Dragomirc** [comment]
The Forget password functionality to be implemented on the next build
