### ISSUE TITLE
SQL queries

### ISSUE THREAD

**Issue by emilyb7** [fac-12/homesafe#38]
I wanted to make a comment about having long SQL strings in your `/queries` files. 

But then I saw this: 
```js
const sql = file => QueryFile(path.join(__dirname, file), { minify: true });
```
 in your `db_build.js` file. This is great. Why not use something like this everywhere? It's much cleaner and means you can write your SQL commands in `.sql` files so that you get the right syntax highlighting and can indent them nicely etc.

At the moment, all the SQL is kind of hard to read.

**Comment by emilyb7** [comment]
(original suggestion was going to be that you implement something similar (and cooler) yourselves using the `fs` module to read files!)

**Comment by Gbaja** [comment]
@emilyb7 We have used the multiline strings for our queries, please review and close issue when you get a chance.

**Comment by emilyb7** [comment]
cool, looking much better @Gbaja
